// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secret_Message_Viewer.Data;

#nullable disable

namespace Secret_Message_Viewer.Migrations
{
    [DbContext(typeof(AppSettingsDbContext))]
    [Migration("20230416044003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secret_Message_Viewer.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MsgAttributeId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MsgAttributeId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Secret_Message_Viewer.Models.MsgAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Destroyed")
                        .HasColumnType("bit");

                    b.Property<long>("UnixTimeS")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MessageAttributes");
                });

            modelBuilder.Entity("Secret_Message_Viewer.Models.Message", b =>
                {
                    b.HasOne("Secret_Message_Viewer.Models.MsgAttribute", "MsgAttribute")
                        .WithMany()
                        .HasForeignKey("MsgAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MsgAttribute");
                });
#pragma warning restore 612, 618
        }
    }
}
